# Generated by Django 5.0.3 on 2024-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_options_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
    ]
